server:
  port: 8083

spring:
  datasource:
    mongodb:
    url: mongodb://localhost:27017/trazabilidad

jwt:
  secret: 98000c1976f4ae3f369df01403c7ab2c5ffe1267e47e5bc5fdcb54ddf65d3af4

app:
  appDescription: "Trazabilidad MicroServicio"
  appVersion: "1.0.0"

